### ISSUE TITLE
Wheel not available for Alpine

### ISSUE THREAD

**Issue by GushchinD** [sarvensis/dict-picker#1]
Great work, I really appreciate it!

But there is one issue that most users will fall into when they will try to containerise their applications efficiently
It is not possible to install the package in Alpine Python container image.

## How to reproduce:

Assuming we use podman as containers and images management tool

1. Ensure that it is possible to install package in other distribution:

```shell
$> podman run --rm python:3.11.2-bullseye pip install dict-picker
Collecting dict-picker
  Downloading dict_picker-0.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 2.4 MB/s eta 0:00:00
Installing collected packages: dict-picker
Successfully installed dict-picker-0.1.3
```

2. Check installation in Alpine image:

```shell
$> podman run --rm python:3.11.2-alpine pip install dict-picker
ERROR: Could not find a version that satisfies the requirement dict-picker (from versions: none)
ERROR: No matching distribution found for dict-picker

```

**Comment by kitsuned** [comment]
It's unimaginable. Lack of musl support is a great disappointment for Alpine Linux users. :rage1:

**Comment by sarvensis** [comment]
Hello! Thank you for the tip. This problem lies in the python and rust bindings. I will try to get information on how to get around this limitation and fix it in future releases.

**Comment by kitsuned** [comment]
any updates???

**Comment by kitsuned** [comment]
@sarvensis

**Comment by sarvensis** [comment]
Problem solved, please check

**Comment by kitsuned** [comment]
```shell
$ podman run --rm python:3.11-alpine pip install dict-picker
Collecting dict-picker
  Downloading dict_picker-0.1.5-cp311-cp311-musllinux_1_1_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 6.6 MB/s eta 0:00:00
Installing collected packages: dict-picker
Successfully installed dict-picker-0.1.5
```

👍🏻
